<?php
/**
 * Secret Resolver Service.
 *
 * @package PantheonSecretsManager\Service
 */

namespace PantheonSecretsManager\Service;

use PantheonSecretsManager\API\PantheonSecretsAPI;

/**
 * Class SecretResolver
 */
class SecretResolver {



	/**
	 * Secrets repository.
	 *
	 * @var SecretsRepository
	 */
	private SecretsRepository $repository;

	/**
	 * Pantheon Secrets API.
	 *
	 * @var PantheonSecretsAPI|null
	 */
	private ?PantheonSecretsAPI $api = null;

	/**
	 * Constructor.
	 */
	public function __construct() {
		$this->repository = new SecretsRepository();
	}

	/**
	 * Get or create the API instance.
	 *
	 * @return PantheonSecretsAPI|null
	 */
	private function get_api(): ?PantheonSecretsAPI {
		if ( null === $this->api ) {
			try {
				$this->api = new PantheonSecretsAPI();
			} catch ( \Exception $e ) {
				// SDK not available or not configured.
				error_log( 'Pantheon Secrets Manager: Failed to initialize API - ' . $e->getMessage() );
				return null;
			}
		}
		return $this->api;
	}

	/**
	 * Define constants for a specific context.
	 *
	 * @param string $context The load context (plugin, mu_plugin).
	 */
	public function define_constants( string $context ): void {
		// Check if "Secrets Creator Only" mode is enabled.
		if ( get_option( 'pantheon_secrets_creator_only', false ) ) {
			return;
		}

		// TODO: Get environment properly.
		$environment = 'dev';

		$secrets = $this->repository->get_all_by_env( $environment );

		foreach ( $secrets as $secret ) {
			if ( $secret->get_load_context() === $context && $secret->is_constant_enabled() ) {
				$this->define_secret_constant( $secret );
			}
		}
	}

	/**
	 * Define a constant for a secret.
	 *
	 * @param \PantheonSecretsManager\Model\Secret $secret The secret.
	 */
	private function define_secret_constant( $secret ): void {
		$constant_name = $secret->get_php_constant_name();

		if ( ! $constant_name || defined( $constant_name ) ) {
			return;
		}

		$api = $this->get_api();
		if ( ! $api ) {
			return;
		}

		$value = $api->get_secret( $secret->get_pantheon_secret_name() );

		if ( $value ) {
			define( $constant_name, $value );
		}
	}

	/**
	 * Generate the MU-plugin loader.
	 *
	 * @return bool True on success, false on failure.
	 */
	public function generate_mu_plugin_loader(): bool {
		$mu_plugins_dir = WP_CONTENT_DIR . '/mu-plugins';
		if ( ! file_exists( $mu_plugins_dir ) ) {
			if ( ! mkdir( $mu_plugins_dir, 0755, true ) ) {
				return false;
			}
		}

		$loader_path = $mu_plugins_dir . '/pantheon-secrets-loader.php';
		$plugin_path = PANTHEON_SECRETS_MANAGER_PATH . 'pantheon-secrets-manager.php';

		$content = "<?php
/**
 * Pantheon Secrets Manager Loader.
 *
 * This file is auto-generated by the Pantheon Secrets Manager plugin.
 */

if ( file_exists( '$plugin_path' ) ) {
	require_once '$plugin_path';
	
	\$resolver = new \\PantheonSecretsManager\\Service\\SecretResolver();
	\$resolver->define_constants( 'mu_plugin' );
}
";

		return (bool) file_put_contents( $loader_path, $content );
	}
}
